# Generated by Django 6.0.1 on 2026-02-09 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_delivery_otp_delivery_otp_generated_at_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('delivery_otp', 'Delivery OTP'), ('order_status', 'Order Status Update'), ('delivery_completed', 'Delivery Completed')], default='order_status', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('otp', models.CharField(blank=True, help_text='OTP for delivery verification', max_length=6, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to='medicine.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Notification',
                'verbose_name_plural': 'User Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
